name: Github Stats
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  uptade-readme-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Readme Profile
        uses: actions-js/profile-readme@v1
